// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kvwlhnttesofttkmwxsv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt2d2xobnR0ZXNvZnR0a213eHN2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEwOTAwNzAsImV4cCI6MjA1NjY2NjA3MH0.uC8DJYqEBQUnlX5t0UAGtYFKsV4p7SBNIX4kB9iI8_4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);